### ISSUE TITLE
line 29 and 30 double ?

### ISSUE THREAD

**Issue by thunderbolt78** [franzkruhm/Plutus-Scroo#21]
hi i get an error with the sanity check

sanity_1_s = ''
sanity_1_s = ''

i think line 30 should be sanity_2_s ?

after i load the script i get this error, memcache is runing 

C:\temp\Plutus-Scroo-master>python filldb-text.py
connect memcached...
Loading and injecting database
03/16/2022, 13:10:00
DONE LOADING DATABASE: Addresses loadeded in 0.0 seconds!
sanity 1:  sanity 2:
03/16/2022, 13:10:00
Traceback (most recent call last):
  File "C:\temp\Plutus-Scroo-master\filldb-text.py", line 64, in <module>
    ret = client.get(sanity_1_s)
  File "C:\Users\squidnet\AppData\Local\Programs\Python\Python310\lib\site-packages\pymemcache\client\base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "C:\Users\squidnet\AppData\Local\Programs\Python\Python310\lib\site-packages\pymemcache\client\base.py", line 1031, in _fetch_cmd
    self._raise_errors(line, name)
  File "C:\Users\squidnet\AppData\Local\Programs\Python\Python310\lib\site-packages\pymemcache\client\base.py", line 932, in _raise_errors
    raise MemcacheUnknownCommandError(name)
pymemcache.exceptions.MemcacheUnknownCommandError: b'get'

C:\temp\Plutus-Scroo-master>

**Comment by franzkruhm** [comment]
apparently filldb-text.py didnt actually push anything into memcached... are you using a 64 bits version of memcached with the command line options specified in the readme?

**Comment by marssystems** [comment]
Yes - that's a typo. The code should be -

sanity_1_i = random.randint(0, 20000000)
sanity_2_i = random.randint(0, 20000000)
sanity_1_s = ''
sanity_2_s = ''

**Comment by marssystems** [comment]
You need to create a data.txt file with your addresses in - 1 per line.
