### ISSUE TITLE
x

### ISSUE THREAD

**Issue by akxks** [franzkruhm/Plutus-Scroo#23]
a

**Comment by akxks** [comment]
When starting scroo.py

` python3 scroo.py
available threads: 4
sanities: If you find a Bitcoin wallet with a balance, the wallet details will show up here: 
04/16/2022, 03:44:49
thread spawned: 0
thread spawned: 1
thread spawned: 2
thread spawned: 3
Process Process-2:
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adriankoszpek/Plutus-Scroo/scroo.py", line 169, in main
    ret = client.get(sanity_1_s)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in _fetch_cmd
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in <listcomp>
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 373, in check_key
    return check_key_helper(key, allow_unicode_keys=self.allow_unicode_keys,
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 117, in check_key_helper
    raise MemcacheIllegalInputError("Key contains whitespace: %r" % key)
pymemcache.exceptions.MemcacheIllegalInputError: Key contains whitespace: b'If you find a Bitcoin wallet with a balance, the wallet details will show up here:'
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adriankoszpek/Plutus-Scroo/scroo.py", line 169, in main
    ret = client.get(sanity_1_s)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in _fetch_cmd
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in <listcomp>
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 373, in check_key
    return check_key_helper(key, allow_unicode_keys=self.allow_unicode_keys,
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 117, in check_key_helper
    raise MemcacheIllegalInputError("Key contains whitespace: %r" % key)
pymemcache.exceptions.MemcacheIllegalInputError: Key contains whitespace: b'If you find a Bitcoin wallet with a balance, the wallet details will show up here:'
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adriankoszpek/Plutus-Scroo/scroo.py", line 169, in main
    ret = client.get(sanity_1_s)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in _fetch_cmd
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in <listcomp>
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 373, in check_key
    return check_key_helper(key, allow_unicode_keys=self.allow_unicode_keys,
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 117, in check_key_helper
    raise MemcacheIllegalInputError("Key contains whitespace: %r" % key)
pymemcache.exceptions.MemcacheIllegalInputError: Key contains whitespace: b'If you find a Bitcoin wallet with a balance, the wallet details will show up here:'
Process Process-4:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/adriankoszpek/Plutus-Scroo/scroo.py", line 169, in main
    ret = client.get(sanity_1_s)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 619, in get
    return self._fetch_cmd(b'get', [key], False).get(key, default)
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in _fetch_cmd
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 1007, in <listcomp>
    prefixed_keys = [self.check_key(k) for k in keys]
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 373, in check_key
    return check_key_helper(key, allow_unicode_keys=self.allow_unicode_keys,
  File "/usr/local/lib/python3.9/site-packages/pymemcache/client/base.py", line 117, in check_key_helper
    raise MemcacheIllegalInputError("Key contains whitespace: %r" % key)
pymemcache.exceptions.MemcacheIllegalInputError: Key contains whitespace: b'If you find a Bitcoin wallet with a balance, the wallet details will show up here:'

`
